"""Add end_time, location, and mode to study_rooms

Revision ID: 80b51d8f91f5
Revises: 
Create Date: 2025-05-04 02:33:34.870864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b51d8f91f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_rooms', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using="date::date")
        batch_op.alter_column('start_time',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.DateTime(),
               existing_nullable=False,
               postgresql_using="start_time::timestamp without time zone")
        batch_op.alter_column('end_time',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.DateTime(),
               nullable=True,
               postgresql_using="end_time::timestamp without time zone")
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('mode',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_rooms', schema=None) as batch_op:
        batch_op.alter_column('mode',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
